### ISSUE TITLE
Color meaning explanation

### ISSUE THREAD

**Issue by Arkemlar** [carapace-sh/carapace-bin#1651]
### Request

This is not clear nor documented why some proposals are colored (blue) and some are not.
Or is it not a feature but a bug?
Examples:

<img width="734" alt="изображение" src="https://user-images.githubusercontent.com/19671202/231236850-638f6b5b-f45d-4dd7-9696-dffaa1492d58.png">

<img width="498" alt="изображение" src="https://user-images.githubusercontent.com/19671202/231237242-af93293d-6d53-4fe1-8501-2864086b499a.png">

### Proposed solution

Please add explanation about this feature into README.md file.

### Anything else?

I am using zsh with OhMyZsh (carapace source call added at the bottom of .zshrc after all other things initalised)
zsh 5.9 (arm-apple-darwin21.3.0)
OhMyZsh latest master version

**Comment by rsteube** [comment]
Feature. It is based on whether the flag takes an argument.
- white/default: no argument
- blue: one argument
- yellow: optional argument (`--flag=optionalValue`)
- magenta: multiple argumenst (e.g. `nix-build --arg`

Can be configured with `carapace --style carapace.Flag*`

**Comment by rsteube** [comment]
And for commands it is highlighted when there are command groups:

```sh
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
```
![image](https://user-images.githubusercontent.com/9090290/231240018-d8b16b31-383f-4bd2-b53a-438fac683164.png)

**Comment by Arkemlar** [comment]
Can I define such groups (override command-to-groups mapping) for myself?

**Comment by rsteube** [comment]
I've experimented with [overlay](https://rsteube.github.io/carapace-bin/overlay.html#command) for that.
It works but also disables strict flag checking for the command which isn't too desirable.

**Comment by rsteube** [comment]
Oh and order is configurable in zsh itself:

```sh
zstyle ':completion:*:git:*' group-order 'main commands' 'alias commands' 'external commands'
```

**Comment by rsteube** [comment]
https://github.com/rsteube/carapace-bin/discussions/1656

**Comment by rsteube** [comment]
Regarding groups i think the best way at the moment would be to build your own custom command with aliases: https://rsteube.github.io/carapace-bin/spec/examples.html#gyaml

**Comment by rsteube** [comment]
I just added it, there wasn't anything before. There's a `faq` badge now in the readme.
