### ISSUE TITLE
Handling for different versions of CLI tools

### ISSUE THREAD

**Issue by aftix** [carapace-sh/carapace-bin#2317]
As far as I can tell, the completers are either made for the most recent version of the tool, or carapace calls into completions provided by the command itself. Is there any plans to extend carapace completers to support different versions of tools?

**Comment by rsteube** [comment]
For the most part, no.
It would increase the complexity in regards of maintenance too much.
Users are expected to be able to update their system to recent versions.

Most commands don't change so often so apart from slight version shifts this normally doesn't pose too much of an issue.
In the long term completions are better maintained alongside commands to avoid this.

Current alternatives:
- [Overlay](https://carapace-sh.github.io/carapace-bin/overlay.html) as temporary workaround for missing completions
- [Spec](https://carapace-sh.github.io/carapace-bin/spec.html#spec) to replace the internal completer with a custom one
- [Bridges](https://carapace-sh.github.io/carapace-bin/bridges.html) to replace the internal completer with a native one

The completers can be built separately. So if the need arises one could also be adapted and maintained externally for a specific version.
Registering these system-wide (e.g. package install) will be possible with [System Spec](https://github.com/carapace-sh/carapace-bin/issues/1336).
