### ISSUE TITLE
Updating nix completers to include completion for flake APIs

### ISSUE THREAD

**Issue by aftix** [carapace-sh/carapace-bin#2348]
### Request

Currently the completers for tools such as `nix` and `nix-shell` mostly just support the standard (non-flake) commands. I would like to have flake completion as well.

### Proposed solution

I have been toying with a completer for `nix flake ...`. A benefit of flakes is that once the completer is run for a flake, it can be cached forever via the flake's NAR hash. So far, my implementation works for the sub-subcommands of `nix flake`, but it is very slow to parse the JSON output of `nix flake show` since flakes can have many outputs (e.g. the `nixpkgs` flake has quite a lot). Do you have any ideas on speeding this up, since it's pretty unusable currently

**Comment by rsteube** [comment]
No, I don't use nix so don't know much about flakes.

**Comment by rsteube** [comment]
Not for the first invocation. Only the subsequent calls can be cached.
