### ISSUE TITLE
How do I turn off Carapace's ssh completion?

### ISSUE THREAD

**Issue by deanishe** [carapace-sh/carapace-bin#2352]
### Request

I would like to disable Carapace just for ssh (zsh's native ssh completion works *way* better for me).

I've tried adding `ssh: zsh` to `~/.config/carapace/bridges.yaml`, but I'm still seeing Carapace's completions, not the native ones.

### Proposed solution

I assume there's already a way to do this; I just couldn't find it in the docs or figure it out.

**Comment by rsteube** [comment]
https://carapace-sh.github.io/carapace-bin/setup/environment.html#carapace_excludes
