### ISSUE TITLE
git: Filename completion with directory symlinks

### ISSUE THREAD

**Issue by saviola777** [carapace-sh/carapace-bin#2359]
### Current Behavior

When there's a symlink anywhere in the directory hierarchy to the current directory, filename completion will create a relative path to the symlink target, effectively breaking filename completion.

### Expected Behavior

Completion should work for the current directory regardless of whether there's a symlink anywhere in the directory hierarchy.

### Steps To Reproduce

With the default config:

```bash
mkdir /tmp/a
ln -s /tmp/a /tmp/b
cd /tmp/b
git clone <some repo> test
cd test
touch some_file
git add som<Tab> # will not offer completion
git add <Tab> # will complete to ../../a/test/some_file
```

### Version

1.0.1

### OS

- [X] Linux
- [ ] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [X] Zsh

**Comment by rsteube** [comment]
I can imaging that there's still something amiss with symlinks.
But following the given example it does complete `some_file` for me for both cases.

**Comment by saviola777** [comment]
Thanks for the feedback, maybe it's something in my configuration / environment that's the issue, I'll try to see if I can identify it.

**Comment by dougg0k** [comment]
Same issue here, I thought to be the shell, but it was carapace. It works with fish autocompleter though.

**Comment by rsteube** [comment]
Urks, so I can see something missing with the directory symlinks.
But regarding `git add` it doesn't look like it accepts anything beyond a directory symlink:
```sh
moep on  master [?]                                                
esh ❯ ls -T
.
├── one
│  ├── a
│  ├── b
│  └── c
└── two -> one
error: no candidates
error: no candidates
moep on  master [?] 
esh ❯ git add two/b
fatal: pathspec 'two/b' is beyond a symbolic link
Exception: git exited with 128
```

**Comment by saviola777** [comment]
> In this case probably due to the real folder being on a different mounted disk.

That's the case for me as well. Sorry, didn't think to include that information.

**Comment by rsteube** [comment]
The information was enough, I must have testet it in the wrong shell :man_facepalming:.
The completion is generated using `git status` and determining the relative path from current work directory to `${GIT_ROOT}/${CHANGE}`.

Seems there is a difference beween zsh and elvish regarding symlinks.
When changing to `/tmp/b/...` in zsh the workdir uses the symlink path. Hence the `../../` relative path to the git root in`/tmp/a/`.
But in elvish the workdir becomes the actual dir (`/tmp/a/...`) so the issue doesn't appear there.
