### ISSUE TITLE
make: support directory selection with '-C'

### ISSUE THREAD

**Issue by BatmanAoD** [carapace-sh/carapace-bin#2370]
### Current Behavior

`make -C <dir> <tab>` prints `ERR  _`.

### Expected Behavior

`make -C <dir>` selects the directory containing the `Makefile`. Standard bash-completion for `make` supports this, so if `<dir>` contains a Makefile with targets `foo` and `bar`, then `make -C <dir> <tab>` produces `foo` and `bar` as completions.

### Steps To Reproduce

Create a Makefile with some targets. Move to a different directory. Type `make -C <dir with makefile>` and hit `tab`.

### Version

1.0.1

### OS

- [ ] Linux
- [X] OSX
- [ ] Windows

### Shell

- [X] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

I found [this pull request](https://github.com/carapace-sh/carapace-bin/pull/1797), but I'm not sure what it does. It does not provide special behavior for the `-C` flag.

**Comment by rsteube** [comment]
Yeah, seems I didn't test it. The PR is correct, but I left the code in the action, which breaks it as the folder is already changed at that time.
