### ISSUE TITLE
nix: flake output completion

### ISSUE THREAD

**Issue by Atemu** [carapace-sh/carapace-bin#2374]
### Request

#2350 avoided adding these because fetching these was thought to be too slow (https://github.com/carapace-sh/carapace-bin/issues/2348).

This is however quite an essential feature using the nix CLI effectively.

cc @aftix 

### Proposed solution

Nix has built-in support for completions, couldn't those be leveraged?

`NIX_GET_COMPLETIONS=2 nix build nixpkgs#` instantly returns a list of completions.

**Comment by rsteube** [comment]
Need to have a look at it, but should have the same issue.
You probably get instant results because you have already invoked it before.

The problem is the first invocation. E.g. there is one nix command that triggers the channel download, which is like ~15mb as far as i remember.
Anything above 100ms starts to feel slow in shell completion. Couple of seconds are fine when it is apparrent to the user that remote data needs to be fetched.
But things like this simply block for quite a long time without any feedback. So it has to be a task detached from the shell completion.
Nothing too complicated, but needs a generic concept as other commands have this issue as well.

**Comment by Atemu** [comment]
Indeed it has that issue. I pin my nixpkgs, so it is almost always cached for me.

It's honestly not that huge of an issue though IMHO. Better wait a few seconds every so often than to have no completion at all. It's the same with regular upstream bash completions, so, while obviously not ideal, this is intended behaviour.

**Comment by aftix** [comment]
With flakes, the time to generate the completions are much faster than using channels, but the first time running the completions command on a flake still takes ~2ish seconds to generate, even if used on a flake located in a local directory.

**Comment by haennes** [comment]
For the NixOS users looking for solutions: I posted mine [here](https://github.com/carapace-sh/carapace-bin/issues/2375#issuecomment-2543186688)
Before i found out about carapace i just used the default completions for nix. These are blocking for quite some time. In my case sometimes upwards of 20s. 
However IMHO it is better have a really slow completion than to have (basically none at all)
As a flake and nixos user, who are usually accustomed to waiting, having tab complete being fast, but actually useless for doing anything with local flakes, I would like it to be blocking.

**Comment by rsteube** [comment]
I don't mind it being a bit slow, so I'm not against adding it.
I just don't want it to randomly download  a ~15MB channel without any user feedback.

**Comment by aftix** [comment]
I did a little more digging. NIX_GET_COMPLETIONS takes a number which is the argument to complete (starting at 0). It is possible to first do something like `NIX_GET_COMPLETIONS=2 nix build nixpkgs` to check if the flake is in the registry then `NIX_GET_COMPLETIONS=2 nix build nixpkgs#<what the user wants to complete>` can just return no entries if the flakeref before `#` isn't already in the registry. So, it is entirely possible to only complete things that are local paths or things that don't need to download from the network. This mechanism also returns a simple list of names for the registry check, so nix does the parsing of `nix regististry list` to see what's available for us here.
