### ISSUE TITLE
Generate competions for arbitrary shell

### ISSUE THREAD

**Issue by ClementNerma** [carapace-sh/carapace-bin#2382]
### Request

Hi!

I'm currently working on my own shell (named ReShell) and I'd like to use Carapace to provide common commands completion.

But it seems like Carapace is only designed to provide completions for specific shells.

### Proposed solution

A good approach IMO could be to have something like an `arbitrary` shell name that would provide completions as JSON, with or without arguments, and without doing any escaping. It would be up to the receiving shell to handle all of these.

**Comment by rsteube** [comment]
There's `carapace COMMAND export "" ARG...`.

```elvish
esh ❯ carapace git export git comm
{"version":"v1.0.0","messages":[],"nospace":"","usage":"","values":[{"value":"commit","display":"commit","description":"Record changes to the repository","style":"blue","tag":"main commands"},{"value":"commit-graph","display":"commit-graph","description":"Write and verify Git commit-graph files","style":"dim yellow","tag":"low-level manipulator commands"},{"value":"commit-tree","display":"commit-tree","description":"Create a new commit object","style":"dim yellow","tag":"low-level manipulator commands"}]}
```

See [Export](https://carapace-sh.github.io/carapace/carapace/export.html?highlight=export#export).

**Comment by ClementNerma** [comment]
Nice! Seems like it.

Thanks :)
