### ISSUE TITLE
Document how to install

### ISSUE THREAD

**Issue by electriquo** [carapace-sh/carapace-bin#2384]
### Request

The documentation has a [Getting Started](https://github.com/carapace-sh/carapace-bin#getting-started) section that specifies how to integrate Carapace, but does not specify how to install Carapace.

### Proposed solution

Document how to install Carapace.

### Anything else?

Would love to see HomeBrew formula for this

```shell
brew install carapace
```

**Comment by rsteube** [comment]
I think it's best to remove it from the readme completely and just direct people to [Installation](https://carapace-sh.github.io/carapace-bin/installation.html).
I've got a [homebrew tap](https://carapace-sh.github.io/carapace-bin/installation.html#homebrew).
