### ISSUE TITLE
Carapace setup not working

### ISSUE THREAD

**Issue by electriquo** [carapace-sh/carapace-bin#2387]
### Current Behavior

I read [Bash setup guide](https://carapace-sh.github.io/carapace-bin/setup.html#bash) and tried to setup Carapace into my shell. Carapace didn't work for me although the its function were there

```shell
$ declare -F | grep -E '^(declare -f ){1}(get|(un)?set|_carapace){1}'
declare -f _carapace_lazy
declare -f get-env
declare -f set-env
declare -f unset-env
```
I was looking whether something overridden or has a conflict with Caraspace, but there was none.
The only thing that worked for me, was placing the setup commands at the very end of my shell profile file.

### Expected Behavior

Carapace setup could appear anywhere on the shell profile files and still get activated

### Steps To Reproduce

1. Add Carapace setup (see below)
2. Start a new shell session
3. Optionally, execute `declare -F | grep -E '^(declare -f ){1}(get|(un)?set|_carapace){1}'` to verify Carapace setup occurred
4. Navigate to a Git repository
5. Type in [`git sh` and press the tab key](https://carapace-sh.github.io/carapace-bin/setup.html)

### Assumptions

1. Linux OS (also holds for macOS though the commands below are slightly different)
6. Bash shell
7. `~/.bash_profile` exists, non-empty, has commands in it excluding Carapace setuo and is loaded when the user logs in

#### Add Carapace

The following will add Carapace setup at the first line of the `~/.bash_profile` file if it is not already there

```bash
CMD='source <(carapace _carapace)'
FILE=~/.bash_profile

grep -qxF "$CMD" "$FILE" || sed -i "1s/^/${CMD}\n/" "$FILE"
```

#### Remove Carapace

The following will remove Carapace when it was [added as above](#add-carapace)

```bash
sed -i '1d' "$FILE"
```

### Version

1.0.2

### OS

- [X] Linux
- [X] OSX
- [ ] Windows

### Shell

- [X] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
Hmm..
You've got this issue on Linux **and** OSX? Anything in your `.bashrc` that might interfere with carapace?
Which Bash version have you?

**Comment by rsteube** [comment]
So on both systems it works when you put it into `~/.bash_profile` or call it manually in a running shell with `source <(carapace _carapace)`?
If so I'd assume there is either some interferance with other entries in `.bashrc` or the shell isn't correctly detected (use `source <(carapace _carapace bash)`).
The functions being present as you wrote should mean that the detection is fine though :thinking: .

**Comment by rsteube** [comment]
Carapace has a 2-step process registering the completion:
```sh
_carapace_lazy() { # initial script registered for completion
  source <(carapace $1 bash) # source actual completion script on first tab (e.g. for git)
   $"_$1_completion" # execute the actual completion script (function) so that they are returned for the first tab as well
}
```

There could be something interfering with line 3 calling the old script. But I haven't encountered something like this in a long time (did in the past though).

**Comment by rsteube** [comment]
Try sourcing just the git completion in a fresh shell and see if that works on the first tab:
```sh
source <(carapace git bash)
```

**Comment by rsteube** [comment]
Not at the moment.

In Fish there's an issue where the file based system completions are always loaded.
So when you register a completion and then try to TAB complete the system one gets loaded and overwrites the previously registered one.
I could imaging someting similar happening here, but I don't have this issue with Bash on any of my systems :thinking: .

**Comment by rsteube** [comment]
That is normal behaviour. By sourcing the completion file you are registering a different function for `git`.

**Comment by rsteube** [comment]
So it is fine now?
