### ISSUE TITLE
OpenSUSE OBS Package

### ISSUE THREAD

**Issue by 8bitZeta** [carapace-sh/carapace-bin#2402]
### Request

It would be very nice to have support on OpenSUSE via a dedicated repo that gets updated. I know there is an RPM already, so it's not impossible to use on OpenSUSE, but it would much appreciated nonetheless.

**Comment by rsteube** [comment]
Is it the `rpm` package or the `repository` that needs to be different for OpenSUSE?

**Comment by rsteube** [comment]
I think I just need to update the instructions:

```sh
zypper ar -f https://yum.fury.io/rsteube/ carapace
zypper install carapace-bin
```

I'm looking into moving to https://cloudsmith.com/ which should fix the [signing issue](https://github.com/orgs/carapace-sh/discussions/2383).

**Comment by 8bitZeta** [comment]
I think that will probably clear everything up. Thanks for the quick response!
