### ISSUE TITLE
xonsh support broken due to wrong subprocess handling

### ISSUE THREAD

**Issue by yggdr** [carapace-sh/carapace-bin#2414]
### Current Behavior

carapace uses standard python faculties like `subprocess.run` and `subprocess.Popen` in xonsh code to run itself with various parameters to generate the completion, but those are fraught with problems because xonsh patches quite a bit of the underlying python stdlib to do its thing, and that is currently not really documented. This means that running subprocesses like that might work one day, might not the next.
I myself found that out only recently, see the [discussion starting here](https://github.com/xonsh/xonsh/discussions/5316#discussioncomment-9755928).

Short version is that instead of using the `subprocess` module, use the helper functions and operators like `$()` and `__xonsh__.subproc_captured_*`. I tried to fix that myself, but could only fix the output of `carapace _carapace xonsh`, which is generated in `cmd/carapace/cmd/lazyinit/xonsh.go`. I cannot find where the output of the various `carapace sometool xonsh` gets generated, so I cannot try to fix that one sadly. Pointers are welcome, so I can work on this.

### Expected Behavior

carapace creates xonsh code with correct subprocess handling, and therefore working completions.

### Steps To Reproduce

Install and setup in `xonsh` as per documentation. Try out `less -` followed by `<Tab>` will result in
```
KeyError: 'less'
Completer _carapace_lazy raises exception when gets old_args=('-', 'less -', 5, 6) / completion_context=CompletionContext(command=CommandContext(args=(CommandArg(value='less', opening_quote='', closing_quote='', is_io_redir=False),), arg_index=1, prefix='-', suffix='', opening_quote='', closing_quote='', is_after_closing_quote=False, subcmd_opening=''), python=PythonContext('less -', 6, is_sub_expression=False)):
<class 'KeyError'> - 'less'
```

### Version

master

### OS

- [X] Linux
- [ ] OSX
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [X] Xonsh
- [ ] Zsh

**Comment by yggdr** [comment]
Thank you for that pointer. After fixing the subprocess issues I unfortunately now see a breaking of the tab key for completions :( I'll have to look further into xonsh internals to see if I can pinpoint what's going wrong here.

**Comment by jnoortheen** [comment]
@rsteube is there any reason to create a separate completer for each of the command encountered during runtime ? 
https://github.com/xonsh/xonsh/discussions/5516#discussioncomment-9883497

**Comment by rsteube** [comment]
It reuses the script from the [library](https://github.com/carapace-sh/carapace).
So if something changes in the integration there it has a direct impact here as well without having to fix the script.
Initially done for lazy loading (performance) and consistency.
Xonsh works a bit different though so a more generic approach as in nushell is possible.

**Comment by yggdr** [comment]
I have a branch `fix-xonsh` on my fork of `carapace-bin` that integrates @jnoortheen's code and seems to work great, at least from a cursory test. I have it running right now.

**Comment by rsteube** [comment]
Thanks, I'll have a look later.
