### ISSUE TITLE
fastfetch: doesn't work at all

### ISSUE THREAD

**Issue by CarterLi** [carapace-sh/carapace-bin#2416]
### Current Behavior

Print `failed to eval completer block: Lists are not automatically spread when calling external commands`

### Expected Behavior

Work as expected

### Steps To Reproduce

Type `fastfetch -<tab>`

### Version

1.0.3

### OS

- [ ] Linux
- [X] OSX
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
Is your completer config hardcoded? Nushell added `...` as requirement at some point.

```nu
carapace $spans.0 nushell ...$spans
```
