### ISSUE TITLE
Add developer/contributing documentation

### ISSUE THREAD

**Issue by samuelallan72** [carapace-sh/carapace-bin#2417]
### Request

As a new contributer to the project, it was difficult to figure out how to build and run the project.  (I had to read through the github workflow files and translate that to local commands.)  It would be nice to have a developer doc with information about how to build, run, and test the project, as well as any useful information to contributors (best practices, guidelines, etc.).

**Comment by rsteube** [comment]
Build instructions are here: https://carapace-sh.github.io/carapace-bin/development/build.html
