### ISSUE TITLE
not works on lubuntu 22.04 LTS bash

### ISSUE THREAD

**Issue by 221V** [carapace-sh/carapace-bin#2473]
### Current Behavior

not works on lubuntu 22.04 LTS bash

after install nothing changes in terminal after close and open it again

### Expected Behavior

expected that will work..

### Steps To Reproduce

1. Lubuntu 22.04 LTS
2. QTerminal 0.17.0 with Qt 5.15.3
3.
```
$ echo $0
/bin/bash
```
4. installed as on website instructions --
 ```
[DEB](https://carapace-sh.github.io/carapace-bin/install.html#deb)

Install from [fury.io](https://rsteube.fury.site/)

# /etc/apt/sources.list.d/fury.list
deb [trusted=yes] https://apt.fury.io/rsteube/ /

apt-get update && apt-get install carapace-bin
```
and
```
~$ vim .bashrc
# add
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
source <(carapace _carapace)
```
5.
```
$ carapace -v
1.0.5
```
6. next commands show output in terminal --
 ```
carapace
carapace _carapace
```
so error in .bashrc ?
or what ..

### OS

- [ ] Darwin
- [X] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [X] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2473">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2473/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2473/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Tried it in a `ubuntu:22.04` docker container and works fine with the described steps.
Have you started a new shell so that the `.bashrc` changes are loaded?

**Comment by 221V** [comment]
> Tried it in a `ubuntu:22.04` docker container and works fine with the described steps. Have you started a new shell so that the `.bashrc` changes are loaded?

yes, new terminal was run -- nothing changes ((

**Comment by rsteube** [comment]
You can also have a look at the logs:
```bash
export CARAPACE_LOG=1
# ... (invoke completion)
cat /tmp/carapace/carapace.log
```

**Comment by 221V** [comment]
> Try loading it manually and see if completions work:
> 
> ```shell
> source <(carapace _carapace)
> ```
> 
> Also try with explicit `bash` to see if the detection is an issue.
> 
> ```shell
> source <(carapace _carapace bash)
> ```

```
$ carapace
# and
$ carapace _carapace
# and
$ carapace _carapace bash
```
returns something to console,
but
```
$ source <(carapace _carapace)
$ source <(carapace _carapace bash)
```
does nothing..

https://pastebin.com/Hx52FqVb

**Comment by 221V** [comment]
> You can also have a look at the logs:
> 
> ```shell
> export CARAPACE_LOG=1
> # ... (invoke completion)
> cat /tmp/carapace/carapace.log
> ```

```
$ cat /tmp/carapace/carapace.log
2024/08/11 17:16:34.546802 bash updating shims
2024/08/12 13:56:14.917921 bash updating shims
```
I not understand, why nothing..
