### ISSUE TITLE
Framework-agnostic completion

### ISSUE THREAD

**Issue by ClementNerma** [carapace-sh/carapace-bin#2530]
### Request

Hi there!

I'm currently building my own shell, and I'd like to use Carapace to provide completions for it. As it is obviously not supported by Carapace, I would have wanted to know if there was a way to get something like a JSON output for command completion?

### Proposed solution

Add a `raw` subcommand which would work like this:

```shell
carapace raw # list all known commands
carapace raw ls # list all known flags for 'ls'
carapace raw ls /med # list all paths starting with '/med' e.g. '/media'
```

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2530">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2530/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2530/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Yes, see [here](https://github.com/carapace-sh/carapace-bin/issues/2382#issuecomment-2112349140).

**Comment by ClementNerma** [comment]
Oh yeah I totally forgot about that, sorry ^^"
Thanks for your help :)
