### ISSUE TITLE
carapace _carapace | Out-String | Invoke-Expression: az completion throws error resolving sh on Windows

### ISSUE THREAD

**Issue by chrisdoherty-dynata** [carapace-sh/carapace-bin#2557]
### Current Behavior

Autocompletion for the az CLI throws the following error under PowerShell 7 on Windows:

`ERR (sh resolves to executable in current directory (.\sh))`

### Expected Behavior

A list of possible options selectable with Tab, per the standard carapace UI

### Steps To Reproduce

PowerShell 7.4.5 on Windows 11

Last seven lines of `Microsoft.PowerShell_profile.ps1`:
```pwsh
# Load starship
Invoke-Expression (&starship init powershell)

# Load carapace for git command completion
Set-PSReadLineOption -Colors @{ "Selection" = "`e[7m" }
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
carapace _carapace | Out-String | Invoke-Expression
```

starship 1.21.0 and carapace 1.0.7 installed via winget

az CLI 2.65.0 installed via winget

1. Open a new PowerShell window in Microsoft Terminal
2. Type a partial az command (i.e. `az --ver` or `az app`)
3. Hit Tab
4. Carapace throws sh resolve error

### Version

1.0.7

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

I do have Git for Windows installed, which means git bash is installed.  There is no `sh` in my $PATH in PowerShell; `Get-Command sh` returns the 'not recognized` error.

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2557">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2557/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2557/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
related https://github.com/fleetingbytes/powershell-argcomplete-mwe

**Comment by rsteube** [comment]
this is new: https://github.com/kislyuk/argcomplete/blob/252d5296f77457382e4370fc6252cf3abbcab201/argcomplete/finders.py#L123

**Comment by chrisdoherty-dynata** [comment]
I understand PowerShell and Windows are far from carapace's native environment, but it's been so incredibly useful I can't live without it now.  Happy to do any testing necessary to help out with this.

**Comment by rsteube** [comment]
It _should_ work on master now if you want to test it: https://carapace-sh.github.io/carapace-bin/development/build.html

The completion for `az` is simply bridged and still provided by `az`, but the way `argcomplete` works this wasn't possible on windows/powershell before.
I assume it's a fairly recent change seeing [this](https://techcommunity.microsoft.com/t5/azure-tools-blog/azure-cli-supports-tab-completion-on-powershell/ba-p/3829771).
