### ISSUE TITLE
Completion doesn't work by default when program has an `exe` extension

### ISSUE THREAD

**Issue by mcexit** [carapace-sh/carapace-bin#2565]
### Current Behavior

By default PowerShell tab completion for executables adds a `.exe` extension, but carapace expects programs to not have have an extension to lazy load the completions. I was able to work around this by modifying the init script:

```powershell
Invoke-Expression -Command (Out-String -InputObject (carapace.exe _carapace 'powershell')).Replace('$commandAst.CommandElements[0].Value', 'Split-Path -LeafBase -Path "$($commandAst.CommandElements[0].Value)"')
```

### Expected Behavior

I'd expect the carapace init script to complete executables with and without the 'exe' extension by default.

### Steps To Reproduce

1. Use the default init script (`carapace.exe _carapace powershell`).
2. Try tab completing a program that has a completer using the `.exe` extension (`bat.exe`).
3. Now, remove the `.exe` extension and tab completion works.
4. After it loads the completer, now completion works for the '.exe' extension when it didn't before.

### Version

1.0.7

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [x] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2565">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2565/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2565/pledge.svg">
</picture>
</a>

**Comment by BurnerWah** [comment]
this also applies to elvish on windows
