### ISSUE TITLE
Custom spec files not being loaded

### ISSUE THREAD

**Issue by ulisses-cruz** [carapace-sh/carapace-bin#2579]
I've installed carapace:
```zsh
brew install carapace
```

I've added the following lines to my zsh config:
```zsh
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)
```

And added my custom spec .yaml files to `~/.config/carapace/spec/`, but they are not being loaded.

Am I missing something?

**Comment by rsteube** [comment]
1. check if it is actually the path where they are loaded from `carapace -h`
```sh
Specs are loaded from [.../carapace/specs]
```
2. make sure to start a new shell for new specs (or execute `source <(carapace _carapace)`)
3. the spec filename must match the command

**Comment by ulisses-cruz** [comment]
> 1. check if it is actually the path where they are loaded from `carapace -h`
> 
> ```shell
> Specs are loaded from [.../carapace/specs]
> ```

Thanks @rsteube, that was the issue, my installation is loading specs from `~/Library/Application Support/carapace/specs`. 

Is there an environment variable, or another way to set the carapace config dir to a different place?

**Comment by rsteube** [comment]
Yes, that's the default [UserConfigDir](https://pkg.go.dev/os#UserConfigDir) on mac (examples in the docs often just show the linux version).
You can set [XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/latest/) which carapace acknowledges on all operation systems, but it will likely affect other commands as well.
