### ISSUE TITLE
PowerShell: Long startup time

### ISSUE THREAD

**Issue by fleimgruber** [carapace-sh/carapace-bin#2586]
### Current Behavior

PowerShell startup takes 15-20 seconds.

### Expected Behavior

PowerShell startup is faster, ideally 1-3 seconds.

### Steps To Reproduce

pwsh 7.4.6
1. PowerShell profile containing `carapace _carapace | Out-String | Invoke-Expression`

### Version

1.0.7

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2586">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2586/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2586/pledge.svg">
</picture>
</a>

**Comment by fleimgruber** [comment]
never mind, I debugged time with `echo ...` when I should have used https://www.powershellgallery.com/packages/PSProfiler/1.0.5.0 which identified another line as the culprit, carapace is not at fault.

**Comment by rsteube** [comment]
Hmm...got to test that on windows myself.
Sourcing it on linux takes ~350ms, which is slow, but...

ah, ok :)
