### ISSUE TITLE
rg/ripgrep update 14.1.1

### ISSUE THREAD

**Issue by munzirtaha** [carapace-sh/carapace-bin#2618]
### Command

rg

### Version

14.1.1

### Release

https://github.com/BurntSushi/ripgrep/releases/tag/14.1.1

### Anything else?

I needed a completer to nushell so I am trying carapace. I usually alias `rg` to `rg --hyperlink-format=kitty` and found completion doesn't work because that flag is not defined in `rg_completer`. So, I added it among other flags and improved things a bit with PR #2617 

However, I have some questions:
First, is there a way for carapace to just ignore missing flags?

Second, `rootCmd.Flags().BoolP("case-sensitive", "s", false, "Search case sensitively.")` is using `false` as the default value though the default for `rg` search is case-sensitive, so I changed it to `true`. How is this going to affect autocomplete practically? Afterall, the default behavior is defined by `ripgrep` not by the value stated here.

Third, it seems like Bool() and BoolP() would allow `--case-sensitive=<TAB>` to give two values `true` and `false` which is wrong because this is a toggle flag that doesn't accept a value. I kept the patch simple and followed the current procedure but not sure whether this is the correct way to handle it.

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2618">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2618/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2618/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
> First, is there a way for carapace to just ignore missing flags?

With [CARAPACE_LENIENT](https://carapace-sh.github.io/carapace-bin/setup/environment.html#carapace_lenient), but that has some implications.
For unknown flags it can't be determined if they take an argument, so they are just handled as bool.
This is a generic change so an [overlay](https://carapace-sh.github.io/carapace-bin/overlay.html) might provide a better alternative.
But both should be seen only as temporary workarounds.

> Second, rootCmd.Flags().BoolP("case-sensitive", "s", false, "Search case sensitively.") is using false as the default value though the default for rg search is case-sensitive, so I changed it to true. How is this going to affect autocomplete practically? Afterall, the default behavior is defined by ripgrep not by the value stated here.

Defaults aren't really relevant for the external completer unless they are used in a contextual completion.
In most cases they are currently left out. Doesn't hurt to add them though.

> Third, it seems like Bool() and BoolP() would allow --case-sensitive=<TAB> to give two values true and false which is wrong because this is a toggle flag that doesn't accept a value. I kept the patch simple and followed the current procedure but not sure whether this is the correct way to handle it.

Current behaviour of carapace is to provide completions as [cobra](https://github.com/spf13/cobra) can parse them.
There are indefed differences between commands (e.g. for some the attached variant is mandatory).
At the moment there is no way to enforce a specific behaviour, but rather left to the user to _know_ about a commands unique requirements.

**Comment by munzirtaha** [comment]
Thanks for the clarifications and merging. Closed with fix #2617
