### ISSUE TITLE
eza: Issue with time-style flag

### ISSUE THREAD

**Issue by mathomp4** [carapace-sh/carapace-bin#2631]
### Current Behavior

When I try and tab-complete with `eza` with my preferred `--time-style=long-iso` option:

```
❯ eza --time-style=long-iso <tab>
invalid argument "long-iso" for "--time-style" flag: strconv.ParseBool: parsing "long-iso": invalid syntax
```

### Expected Behavior

Tab completion should work. 

### Steps To Reproduce

1. Try to tab complete: `eza --time-style=long-iso `

### Version

1.1.0

### OS

- [X] Darwin
- [ ] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [X] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2631">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2631/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2631/pledge.svg">
</picture>
</a>

**Comment by mathomp4** [comment]
Just did some tests and it looks like *any* `--time-style` flag might trigger the issue. Per the man page:
```
       --time-style=STYLE
              How to format timestamps.  Valid timestamp styles are `default', `iso', `long-iso', `full-iso', `relative', or a custom style `+<FORMAT>' (e.g.,
              `+%Y-%m-%d %H:%M' => `2023-09-30 13:00').
```

**Comment by rsteube** [comment]
The `--help` output is missing the argument for some flags, so I got some wrong flag types when parsing it.
I fixed that and added completions, but seems I still got the flag type wrong for this one.

**Comment by mathomp4** [comment]
@rsteube Thanks! I'll be on the lookout for v1.2 or v1.1.1 or whatever is next.

Luckily this is a flag I do not *need* so no big hinderance if it takes a while. It's just for prettifying. (Though I didn't know about the `full-iso` option and yikes! That be *wiiiiide*.)

**Comment by rsteube** [comment]
You can try the nightly later: https://carapace-sh.github.io/carapace-bin/install/selfupdate.html
