### ISSUE TITLE
Wrong ANSI color names

### ISSUE THREAD

**Issue by munzirtaha** [carapace-sh/carapace-bin#2641]
### Current Behavior

The color names in pkg/actions/color/ansi.go are not following [ANSI](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). If I am not missing something obvious, I will submit a PR

### Expected Behavior

e.g. Instead of
"31", "Maroon", style.XTerm256Color(1),
It should be
"31", "Red", style.XTerm256Color(1),

### Version

v1.1.0

### OS

- [ ] Darwin
- [X] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2641">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2641/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2641/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
fixed with #2642
