### ISSUE TITLE
Breaking Regression in carapace-bin 1.1.0

### ISSUE THREAD

**Issue by mcexit** [carapace-sh/carapace-bin#2645]
### Current Behavior

It appears that there is a breaking bug in carapace-bin 1.1.0, specifically in commit fafc1fa:

```
$completer = $commandAst.CommandElements[0].Value.trimend(".exe")
```

The [TrimEnd](https://learn.microsoft.com/dotnet/api/system.string.trimend) method in PowerShell doesn't work as intended here. What this actually does is remove any of those characters from the end of the string. `carapace.exe` becomes `carapac` & `rclone.exe` becomes `rclon`. I was trying to figure out why some completions were working & others weren't.

### Expected Behavior

The $completer variable should get assigned to the correct command name.

### Steps To Reproduce

1. Using carapace-bin try to complete any command that ends with the characters `e` or `x`

### Version

1.1.0

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

There are a few ways to get the command without `.exe` in PowerShell, but this ain't one of them.

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2645">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2645/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2645/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
duh! - thanls
