### ISSUE TITLE
One more bug in EXE extension for PowerShell

### ISSUE THREAD

**Issue by mcexit** [carapace-sh/carapace-bin#2648]
### Current Behavior

You've done amazing fast work in trying to resolve #2565. I saw today though in v1.1.1 when trying to complete a program with an EXE extension that it still wasn't working. Fortunately, this was immediately obvious to me as to why.

In #2646 you use the .NET `Replace` method which doesn't support regex, unlike its `-replace` PowerShell counterpart. You could use `$completer = $commandAst.CommandElements[0].Value.Replace(".exe", "")` instead, which should generally be fine. But `$completer = $commandAst.CommandElements[0].Value -replace '\.exe$', ''` is prob the more correct way, or you could also look into `Split-Path -LeafBase`.

I feel bad cause I know it is one nuance after another with PowerShell,

### Expected Behavior

Both command & command.exe completions should work.

### Steps To Reproduce

1. Try completion with EXE file extension

### Version

1.1.1

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2648">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2648/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2648/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Oof - I had `-replace` before and thought it is just a different way to write it.
Should have tested it on Windows, I can see why it seemed to work on Linux.

**Comment by rsteube** [comment]
Went with `-replace` as it's the easiest to understand when I get back to this at some point.

Seems `.bat` files on `PATH` can also be executed without extension.
Might need to give that some thought at some point as well as there are executables with extensions other than `.exe` on windows.

**Comment by rsteube** [comment]
Yeah, gonna have another look at all this in the future. `$env:PATHEXT` sounds good.
