### ISSUE TITLE
gcloud: Killed by signal in _gcloud_completion after 0s

### ISSUE THREAD

**Issue by polo871209** [carapace-sh/carapace-bin#2658]
### Current Behavior

Hi Community,

Here is my current .zshrc:

```zsh
# Auto Complete
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)
```
When I type gcloud than tab, here is the output

```zsh
gcloud
exit status 1
```

When I Ctrl C out of the completion, here is the error

```zsh
gcloud
Killed by signal in _gcloud_completion after 0s
```

### Steps To Reproduce

```bash
carapace --version
carapace-bin 1.1.0
```

### Version

carapace-bin 1.1.0

### OS

- [X] Darwin
- [ ] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [X] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2658">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2658/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2658/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Urks, so this is due to https://github.com/carapace-sh/carapace-bridge/pull/212 .
`argomplete` used file descriptors for output that aren't available in powershell/windows (fd 8/9).
Recent versions allow setting an environment variable to use a file instead.

`gclould` must still be on an old version of `argcomplete`.
